version: '3.8'

services:
  everly-growth-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: everly-growth-tracker
    restart: unless-stopped
    ports:
      - "9378:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - everly-network

networks:
  everly-network:
    driver: bridge
