import type { MilestoneItem } from './types'

// Subset of common milestones 0-24 months. Can be expanded later.
export const defaultMilestones: MilestoneItem[] = [
  {
    id: 'smile-social-2m',
    title: 'Smiles socially',
    description: 'Smiles at people or in response to voices',
    ageStartMonths: 1,
    ageEndMonths: 3,
    category: 'social',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'roll-over-4m',
    title: 'Rolls over',
    description: 'Rolls from tummy to back or back to tummy',
    ageStartMonths: 3,
    ageEndMonths: 6,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'sit-6m',
    title: 'Sits without support',
    description: 'Sits briefly without using hands for support',
    ageStartMonths: 5,
    ageEndMonths: 8,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'crawl-9m',
    title: 'Crawls',
    description: 'Moves on hands and knees',
    ageStartMonths: 7,
    ageEndMonths: 11,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'babble-9m',
    title: 'Babbles',
    description: 'Says consonant-vowel sounds like “ba-ba”',
    ageStartMonths: 6,
    ageEndMonths: 10,
    category: 'language',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'stand-12m',
    title: 'Pulls to stand',
    description: 'Pulls up to standing and cruises furniture',
    ageStartMonths: 9,
    ageEndMonths: 13,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'first-words-12m',
    title: 'Says first words',
    description: 'Says “mama”, “dada” or other words with meaning',
    ageStartMonths: 10,
    ageEndMonths: 14,
    category: 'language',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'walk-15m',
    title: 'Walks independently',
    description: 'Takes several steps without support',
    ageStartMonths: 12,
    ageEndMonths: 18,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'two-words-24m',
    title: 'Uses two-word phrases',
    description: 'Combines words like “more milk”',
    ageStartMonths: 20,
    ageEndMonths: 26,
    category: 'language',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'stack-blocks-18m',
    title: 'Stacks 2–3 blocks',
    description: 'Stacks small blocks or objects',
    ageStartMonths: 15,
    ageEndMonths: 20,
    category: 'cognitive',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'scribbles-18m',
    title: 'Scribbles with crayon',
    description: 'Makes marks on paper with a crayon or marker',
    ageStartMonths: 14,
    ageEndMonths: 20,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'points-body-parts-18m',
    title: 'Points to body parts',
    description: 'Points to eyes, nose, mouth when asked',
    ageStartMonths: 16,
    ageEndMonths: 22,
    category: 'language',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'run-20m',
    title: 'Runs steadily',
    description: 'Begins to run without falling often',
    ageStartMonths: 18,
    ageEndMonths: 24,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'throws-ball-20m',
    title: 'Throws a ball',
    description: 'Throws a ball forward',
    ageStartMonths: 18,
    ageEndMonths: 24,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'follows-2-step-24m',
    title: 'Follows 2-step instructions',
    description: 'Understands and follows two-step directions',
    ageStartMonths: 22,
    ageEndMonths: 28,
    category: 'cognitive',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'kicks-ball-24m',
    title: 'Kicks a ball',
    description: 'Kicks a ball forward',
    ageStartMonths: 20,
    ageEndMonths: 26,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'names-pictures-24m',
    title: 'Names pictures/objects',
    description: 'Names familiar pictures in a book',
    ageStartMonths: 22,
    ageEndMonths: 28,
    category: 'language',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'jumps-24m',
    title: 'Jumps with both feet',
    description: 'Leaves the ground with both feet',
    ageStartMonths: 22,
    ageEndMonths: 30,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'sorts-shapes-24m',
    title: 'Sorts shapes and colors',
    description: 'Matches shapes or colors with toys/puzzles',
    ageStartMonths: 22,
    ageEndMonths: 30,
    category: 'cognitive',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'uses-pronouns-26m',
    title: 'Uses pronouns (me, you, mine)',
    description: 'Begins to use simple pronouns correctly',
    ageStartMonths: 24,
    ageEndMonths: 30,
    category: 'language',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'climbs-stairs-30m',
    title: 'Climbs stairs with support',
    description: 'Walks up and down stairs holding a railing',
    ageStartMonths: 24,
    ageEndMonths: 32,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'builds-tower-30m',
    title: 'Builds a 4–6 block tower',
    description: 'Stacks more blocks accurately',
    ageStartMonths: 24,
    ageEndMonths: 32,
    category: 'cognitive',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'speaks-50-words-30m',
    title: 'Speaks ~50 words',
    description: 'Vocabulary expands to around 50 words',
    ageStartMonths: 24,
    ageEndMonths: 30,
    category: 'language',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'pretend-play-30m',
    title: 'Engages in simple pretend play',
    description: 'Feeds a doll, talks on a toy phone',
    ageStartMonths: 24,
    ageEndMonths: 34,
    category: 'social',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'pedal-trike-36m',
    title: 'Pedals a tricycle',
    description: 'Pedals and steers a tricycle or ride-on toy',
    ageStartMonths: 30,
    ageEndMonths: 38,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'speaks-3-4-word-phrases-36m',
    title: 'Uses 3–4 word sentences',
    description: 'Forms short sentences to express needs',
    ageStartMonths: 30,
    ageEndMonths: 36,
    category: 'language',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'understands-turn-taking-36m',
    title: 'Understands turn-taking',
    description: 'Begins to share/take turns with guidance',
    ageStartMonths: 30,
    ageEndMonths: 38,
    category: 'social',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'draws-circle-36m',
    title: 'Draws a circle',
    description: 'Imitates drawing shapes like a circle',
    ageStartMonths: 32,
    ageEndMonths: 40,
    category: 'motor',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
  {
    id: 'answers-what-where-36m',
    title: 'Answers “what”/“where” questions',
    description: 'Understands and answers simple questions',
    ageStartMonths: 32,
    ageEndMonths: 40,
    category: 'language',
    level: 'none',
    levelHistory: [],
    createdAtIso: new Date().toISOString(),
  },
]


